### ISSUE TITLE
Setting up the rest api

### ISSUE THREAD

**Issue by kvanla** [xhibit/Teletask-api#28]
I have a teletask micros+, and would like to setup a rest api running on my local debian server which also runs home assistant which I want to use to controle my domotica. I have some questions on how to setup this project. Do I need a license to actualy try this all out (if so how much does this license cost and is it also a yearly subscription or is it only once)? 
I have build the whole project using inteliji and Maven and got all the jar/war files, however how do I deploy the rest war file, since this doesn't have a main (I have the tds-config file)?

I have also tried the Jeletask @ridiekel  version since that one was still being maintained, however also failed to see a main or documentation on how to deploy.

**Comment by ridiekel** [comment]
You indeed need a license installed on the central unit. I cannot give you current pricing details however. It is a license for life, so no recurring cost.

I am maintaining the fork now, and during the summer I am planning on releasing a version containing a docker image that can connect to an MQTT broker, and sends all data using MQTT.

**Comment by kvanla** [comment]
Thx for the info, I am currently trying https://github.com/sillevl/node-teletask which seems to work with a trial doip license. There is also a https://github.com/sillevl/teletask-mqtt mqtt broker which I am also trying at the moment.

**Comment by LeGiGi** [comment]
Hi,

I am new with the rest api and wish to integrate the Teletask rest api with Home Assistant. So far I am struggling to get this Teletask-api installed on a Debian VM.
You mentioned in your 24 June that you were working on a version containing a docker image that can connect to an MQTT broker. Is this Docker image already available? If so can you please share it.

If not, I am new with GIT and I do not know how to get this to work on my Debian server.
I managed to download the file Teletask-api-master.zip with wget  https://github.com/xhibit/Teletask-api.git and I also downloaded a copy of the ZIP file but no idea how to proceed.

I have the PICOS at home cabled to the internal network but not the MICROS+ central.
I use Home Assistant and until now use the trial DoIP license on the PICOS to open the central unit port.


Regards,
Geert

**Comment by ridiekel** [comment]
@LeGiGi @kvanla 

I just created a first draft (on the feature/docker branch: https://github.com/ridiekel/jeletask/tree/feature/docker) of what should be a working docker container connecting to MQTT. I also updated the readme file to have somewhat more information. Documentation is not yet complete, but you should already be able to play with it.
Also, there should be some rudimentary support for autodiscovery in home assistant. Since I don't use HA, it's difficult to test :-)

Hope you guys find the time to test. If all goes well, I will try to publish more docs and I will look into publishing the docker image on dockerhub


Regards,
Geroen

**Comment by ridiekel** [comment]
@LeGiGi @kvanla I also enabled the issues tab in github on my repo, apparently this was diabled in my repo. So if you have problems or comments, you can mention them there :-) This repo (https://github.com/xhibit/Teletask-api) is not actively maintained anymore.
